import sys
import os
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../'))
import numpy as np

from src.utils.file_io import (
    get_all_folder_names, load_json, get_all_paths, 
    opencv_distortion_coefficients_to_dictionary,
    write_opencv_calibration_to_xml,
    plt_figure_to_bytes, save_json
    )
from src.utils.image_utils import load_ldr
from src.scanner.calibration import Charuco, Calibration
from src.utils.plotter import Plotter
from src.reconstruction.metashape import save_opencv_extrinsics_for_metashape

MINIMUM_NUM_MARKERS = 5
ERROR_THRESHOLD = 1.

# for HTML report generation
import base64
import xml.etree.ElementTree as etree

def generate_report(path: str, calibrations: dict):
    """
    This function was mostly generated by Claude. It generates an HTML
    report of each camera calibration (with plots and text).
    Generate a self-contained HTML calibration report from a `calibrations` dict.

    Expected `calibrations` structure
    ----------------------------------
    calibrations = {
        "camera_id_0": {
            "K":            np.ndarray,  # 3×3 intrinsic matrix
            "dist_coeffs":         np.ndarray,  # distortion coefficients (k1,k2,p1,p2[,k3…])
            "resolution":   (width, height),
            "per_view_errors": np.ndarray,  # shape (N,) or (N,1) – RMS per image
            ....
        },
        "camera_id_1": { … },
    }

    """
    import datetime
    title = '{} Calibration Report'.format(datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ"))

    root = etree.Element("html", lang="en")
    root.append(_build_head(title))
    body = etree.SubElement(root, "body")

    # ── Page header ──────────────────────────────────────────────────────────
    header = etree.SubElement(body, "header")
    h1 = etree.SubElement(header, "h1")
    h1.text = title

    summary_bar = etree.SubElement(header, "div", attrib={"class": "summary-bar"})
    _append_summary_chips(summary_bar, calibrations)

    # ── Navigation ───────────────────────────────────────────────────────────
    nav = etree.SubElement(body, "nav", attrib={"id": "toc"})
    nav_label = etree.SubElement(nav, "span", attrib={"class": "nav-label"})
    nav_label.text = "Jump to camera:"
    for cam_id in calibrations:
        a = etree.SubElement(nav, "a", attrib={"href": f"#{_slug(cam_id)}"})
        a.text = cam_id

    main = etree.SubElement(body, "main")

    # ── Per-camera sections ───────────────────────────────────────────────────
    for cam_id, cal in calibrations.items():
        section = etree.SubElement(
            main, "section",
            attrib={"class": "camera-section", "id": _slug(cam_id)},
        )

        # Section heading
        h2 = etree.SubElement(section, "h2")
        h2.text = cam_id

        # ── Row 1 : quick-stats chips ────────────────────────────────────────
        stats_row = etree.SubElement(section, "div", attrib={"class": "stats-row"})
        _append_camera_chips(stats_row, cam_id, cal)

        # ── Row 2 : two-column card grid ─────────────────────────────────────
        grid = etree.SubElement(section, "div", attrib={"class": "card-grid"})

        # Card: Intrinsic matrix K
        _card_intrinsic_matrix(grid, cal.get("K"))

        # Card: Per-view reprojection errors
        _card_per_view_errors(grid, cam_id, cal.get("per_view_errors"))

        # ──────────────────────────────────────────────────────────────────────
        # ► ADD YOUR OWN CARDS HERE

        # Or for plain text / HTML:
        if len(cal.get('invalid_idx')) > 0:
            card = _new_card(grid, title="Invalid images")
            inv = etree.SubElement(card, "invalid")
            
            inv.text = "Images with invalid marker detection: " + \
                " ".join(map(str, cal.get('invalid_labels')))
        

        # --- Undistortion preview ---
        ## plot of camera distortion
        card = _new_card(grid, title="Camera Distortion")
        fig = Plotter.plot_distortion(cal.get('image_shape'),cal.get('K'),cal.get('dist_coeffs'))
        img_bytes = plt_figure_to_bytes(fig)
        _embed_image(card, img_bytes, alt="Camera Distortion")

        # Card: Distortion coefficients
        _card_distortion(grid, cal.get("dist_coeffs"))

        #
        # --- Custom corner-detection plot ---
        ## plot of identified markers
        card = _new_card(grid, title="Detected Markers")
        fig = Plotter.plot_markers(cal.get('clean_img_points'),cal.get('image_shape'),cal.get('K'))
        img_bytes = plt_figure_to_bytes(fig)
        _embed_image(card, img_bytes, alt="detected markers")

        card = _new_card(grid, title="Reprojection Errors")
        num_card = etree.SubElement(card, "total-number")
        num_below = (np.concatenate(cal.get('errors')) < ERROR_THRESHOLD).sum()
        num = len(np.concatenate(cal.get('errors')))
        num_card.text = f'Markers detected: {num}. \n'+\
            f'Markers below {ERROR_THRESHOLD}px error: {num_below} ({(num_below/num*100):2f}%)'
        
        fig = Plotter.plot_reprojection_errors(np.concatenate(cal.get('errors')))
        img_bytes = plt_figure_to_bytes(fig)
        _embed_image(card, img_bytes, alt="reprojection error")

        #### Camera registration
        card = _new_card(grid, title="Camera Registration")
        fig = Plotter.plot_cameras_colmap_style(cal.get('rvecs'),
                                                cal.get('tvecs'),
                                                cal.get('K'),
                                                cal.get('image_shape'),
                                                linewidth=5,
                                                scale=10)
        img_bytes = plt_figure_to_bytes(fig)
        _embed_image(card, img_bytes, alt="camera registration")
        
        # --- Any scalar metrics ---
        # card = _new_card(grid, title="Extra Metrics")
        # _key_value_table(card, {"RMSE": f"{cal['rmse']:.4f} px"}
        #                        
        # ──────────────────────────────────────────────────────────────────────

        ## number of makers, number (and percentage) of markers under 1px error



        ### plot of camera positions and orientations
        
        # Back-to-top link
        btt = etree.SubElement(section, "a", attrib={"href": "#", "class": "back-to-top"})
        btt.text = "↑ back to top"

    # ── Footer ───────────────────────────────────────────────────────────────
    footer = etree.SubElement(body, "footer")
    footer.text = "Generated by calibration_report.py"

    html = b"<!DOCTYPE html>\n"
    html += etree.tostring(root, encoding="UTF-8", method="html", xml_declaration=False)
    with open(path, "wb") as fh:
        fh.write(html)

# ===========================================================================
# ► PUBLIC HELPERS – use these in your own card-building code
# ===========================================================================

def _new_card(parent: etree.Element, title: str) -> etree.Element:
    """
    Append a titled card div to *parent* and return the card body div.

    Usage
    -----
        card_body = _new_card(grid, "My Plot")
        img_bytes = my_function(...)
        _embed_image(card_body, img_bytes)
    """
    card = etree.SubElement(parent, "div", attrib={"class": "card"})
    h3 = etree.SubElement(card, "h3")
    h3.text = title
    body = etree.SubElement(card, "div", attrib={"class": "card-body"})
    return body


def _embed_image(
    parent: etree.Element,
    png_bytes: bytes,
    alt: str = "",
    mime: str = "image/png",
) -> etree.Element:
    """
    Embed *png_bytes* (or any image bytes) as a base64 <img> tag inside *parent*.

    Parameters
    ----------
    parent    : lxml element to append <img> to
    png_bytes : raw image bytes (PNG by default)
    alt       : alt-text
    mime      : MIME type, e.g. "image/png", "image/svg+xml"
    """
    b64 = base64.b64encode(png_bytes).decode()
    img = etree.SubElement(
        parent, "img",
        attrib={"src": f"data:{mime};base64,{b64}", "alt": alt, "class": "plot-img"},
    )
    return img


def _key_value_table(
    parent: etree.Element,
    data: dict[str, str],
) -> etree.Element:
    """Render a simple two-column key/value table."""
    tbl = etree.SubElement(parent, "table", attrib={"class": "kv-table"})
    for k, v in data.items():
        tr = etree.SubElement(tbl, "tr")
        th = etree.SubElement(tr, "th")
        th.text = k
        td = etree.SubElement(tr, "td")
        td.text = str(v)
    return tbl


# ===========================================================================
# Internal helpers – built-in cards
# ===========================================================================

def _card_intrinsic_matrix(parent: etree.Element, K: np.ndarray | None) -> None:
    card_body = _new_card(parent, "Intrinsic Matrix  K")
    if K is None:
        _missing(card_body, "K")
        return

    fx, fy = K[0, 0], K[1, 1]
    cx, cy = K[0, 2], K[1, 2]
    skew = K[0, 1]

    # Rendered matrix
    tbl = etree.SubElement(card_body, "table", attrib={"class": "matrix-table"})
    for row in K:
        tr = etree.SubElement(tbl, "tr")
        for val in row:
            td = etree.SubElement(tr, "td")
            td.text = f"{val:.4f}"

    # Named parameters below
    _key_value_table(card_body, {
        "fx (px)":  f"{fx:.4f}",
        "fy (px)":  f"{fy:.4f}",
        "cx (px)":  f"{cx:.4f}",
        "cy (px)":  f"{cy:.4f}",
        "skew":     f"{skew:.6f}",
        "aspect ratio fy/fx": f"{fy/fx:.6f}" if fx != 0 else "—",
    })


def _card_distortion(parent: etree.Element, dist: np.ndarray | None) -> None:
    card_body = _new_card(parent, "Distortion Coefficients")
    if dist is None:
        _missing(card_body, "dist")
        return

    d = np.asarray(dist).flatten()
    labels = ["k1", "k2", "p1", "p2", "k3", "k4", "k5", "k6",
              "s1", "s2", "s3", "s4", "τx", "τy"]
    _key_value_table(card_body, {
        labels[i] if i < len(labels) else f"d{i}": f"{v:.8f}"
        for i, v in enumerate(d)
    })


def _card_per_view_errors(
    parent: etree.Element,
    cam_id: str,
    per_view_errors: np.ndarray | None,
) -> None:
    card_body = _new_card(parent, "Per-View Reprojection Errors")
    if per_view_errors is None:
        _missing(card_body, "per_view_errors")
        return

    errs = np.asarray(per_view_errors).flatten()
    _key_value_table(card_body, {
        "Views":    str(len(errs)),
        "Mean RMS": f"{errs.mean():.4f} px",
        "Std":      f"{errs.std():.4f} px",
        "Min":      f"{errs.min():.4f} px",
        "Max":      f"{errs.max():.4f} px",
    })

    # ── Inline bar chart (pure SVG, no dependencies) ─────────────────────
    try:
        svg_bytes = _svg_bar_chart(errs, xlabel="View index", ylabel="RMS (px)")
        _embed_image(card_body, svg_bytes, alt="per-view errors", mime="image/svg+xml")
    except Exception as exc:
        note = etree.SubElement(card_body, "p", attrib={"class": "warn"})
        note.text = f"Could not render bar chart: {exc}"

    # ──────────────────────────────────────────────────────────────────────
    # ► REPLACE / AUGMENT the chart above with your own matplotlib figure:
    #
    # import matplotlib.pyplot as plt
    # fig, ax = plt.subplots(figsize=(6, 3))
    # ax.bar(range(len(errs)), errs)
    # ax.set_xlabel("View index"); ax.set_ylabel("RMS (px)")
    # buf = io.BytesIO(); fig.savefig(buf, format="png", bbox_inches="tight")
    # plt.close(fig)
    # _embed_image(card_body, buf.getvalue(), alt="per-view errors")
    # ──────────────────────────────────────────────────────────────────────


# ---------------------------------------------------------------------------
# Summary chips
# ---------------------------------------------------------------------------

def _append_summary_chips(parent: etree.Element, calibrations: dict) -> None:
    chips = {
        "Cameras": str(len(calibrations)),
    }
    all_errs = []
    for cal in calibrations.values():
        if cal.get("per_view_errors") is not None:
            all_errs.extend(np.asarray(cal["per_view_errors"]).flatten().tolist())
    if all_errs:
        chips["Overall mean RMS"] = f"{np.mean(all_errs):.4f} px"
        chips["Overall max RMS"]  = f"{np.max(all_errs):.4f} px"

    for k, v in chips.items():
        chip = etree.SubElement(parent, "div", attrib={"class": "chip"})
        label = etree.SubElement(chip, "span", attrib={"class": "chip-label"})
        label.text = k
        val = etree.SubElement(chip, "span", attrib={"class": "chip-value"})
        val.text = v


def _append_camera_chips(
    parent: etree.Element, cam_id: str, cal: dict
) -> None:
    chips: dict[str, str] = {}

    if cal.get("image_shape"):
        w, h = cal["image_shape"]
        chips["Resolution"] = f"{w} × {h}"

    K = cal.get("K")
    if K is not None:
        chips["fx"] = f"{K[0,0]:.1f} px"
        chips["fy"] = f"{K[1,1]:.1f} px"

    dist = cal.get("dist_coeeffs")
    if dist is not None:
        chips["Dist coeffs"] = str(np.asarray(dist).flatten().shape[0])

    errs = cal.get("per_view_errors")
    if errs is not None:
        e = np.asarray(errs).flatten()
        chips["Views"] = str(len(e))
        chips["Mean RMS"] = f"{e.mean():.4f} px"

    for k, v in chips.items():
        chip = etree.SubElement(parent, "div", attrib={"class": "chip"})
        label = etree.SubElement(chip, "span", attrib={"class": "chip-label"})
        label.text = k
        val = etree.SubElement(chip, "span", attrib={"class": "chip-value"})
        val.text = v


# ---------------------------------------------------------------------------
# Minimal SVG bar chart (zero external deps)
# ---------------------------------------------------------------------------

def _svg_bar_chart(
    values: np.ndarray,
    xlabel: str = "",
    ylabel: str = "",
    width: int = 480,
    height: int = 200,
) -> bytes:
    n = len(values)
    if n == 0:
        raise ValueError("empty array")

    pad_l, pad_r, pad_t, pad_b = 48, 16, 16, 36
    inner_w = width - pad_l - pad_r
    inner_h = height - pad_t - pad_b

    vmax = float(values.max()) * 1.15 or 1.0
    bar_w = max(1, inner_w / n - 1)

    svg = etree.Element("svg", attrib={
        "xmlns": "http://www.w3.org/2000/svg",
        "viewBox": f"0 0 {width} {height}",
        "width": str(width), "height": str(height),
    })

    # Background
    etree.SubElement(svg, "rect", attrib={
        "width": str(width), "height": str(height),
        "fill": "#181c24",
    })

    # Y gridlines + labels
    for frac in [0, 0.25, 0.5, 0.75, 1.0]:
        y = pad_t + inner_h * (1 - frac)
        etree.SubElement(svg, "line", attrib={
            "x1": str(pad_l), "x2": str(pad_l + inner_w),
            "y1": str(y), "y2": str(y),
            "stroke": "#2e3340", "stroke-width": "1",
        })
        txt = etree.SubElement(svg, "text", attrib={
            "x": str(pad_l - 4), "y": str(y + 4),
            "text-anchor": "end", "font-size": "9",
            "fill": "#8892a4", "font-family": "monospace",
        })
        txt.text = f"{vmax * frac:.3f}"

    # Bars
    mean_val = float(values.mean())
    for i, v in enumerate(values):
        x = pad_l + i * (inner_w / n)
        bar_h = (v / vmax) * inner_h
        # color = "#ef4444" if v > mean_val * 2 else "#38bdf8"
        color = "#ef4444" if v > ERROR_THRESHOLD else "#38bdf8"
        etree.SubElement(svg, "rect", attrib={
            "x": str(x), "y": str(pad_t + inner_h - bar_h),
            "width": str(bar_w), "height": str(bar_h),
            "fill": color, "rx": "1",
        })

    # Mean line
    mean_y = pad_t + inner_h * (1 - mean_val / vmax)
    etree.SubElement(svg, "line", attrib={
        "x1": str(pad_l), "x2": str(pad_l + inner_w),
        "y1": str(mean_y), "y2": str(mean_y),
        "stroke": "#fbbf24", "stroke-width": "1",
        "stroke-dasharray": "4 3",
    })
    mean_lbl = etree.SubElement(svg, "text", attrib={
        "x": str(pad_l + inner_w - 2), "y": str(mean_y - 3),
        "text-anchor": "end", "font-size": "9",
        "fill": "#fbbf24", "font-family": "monospace",
    })
    mean_lbl.text = f"mean {mean_val:.4f}"

    # Axes
    etree.SubElement(svg, "line", attrib={
        "x1": str(pad_l), "x2": str(pad_l),
        "y1": str(pad_t), "y2": str(pad_t + inner_h),
        "stroke": "#4b5563", "stroke-width": "1.5",
    })
    etree.SubElement(svg, "line", attrib={
        "x1": str(pad_l), "x2": str(pad_l + inner_w),
        "y1": str(pad_t + inner_h), "y2": str(pad_t + inner_h),
        "stroke": "#4b5563", "stroke-width": "1.5",
    })

    # Axis labels
    if xlabel:
        xl = etree.SubElement(svg, "text", attrib={
            "x": str(pad_l + inner_w / 2),
            "y": str(height - 4),
            "text-anchor": "middle", "font-size": "10",
            "fill": "#8892a4", "font-family": "sans-serif",
        })
        xl.text = xlabel

    if ylabel:
        yl = etree.SubElement(svg, "text", attrib={
            "transform": f"rotate(-90) translate(-{pad_t + inner_h//2},12)",
            "text-anchor": "middle", "font-size": "10",
            "fill": "#8892a4", "font-family": "sans-serif",
        })
        yl.text = ylabel

    return etree.tostring(svg)


# ---------------------------------------------------------------------------
# Head / CSS
# ---------------------------------------------------------------------------

def _build_head(title: str) -> etree.Element:
    head = etree.Element("head")
    meta_charset = etree.SubElement(head, "meta", attrib={"charset": "UTF-8"})
    meta_viewport = etree.SubElement(head, "meta", attrib={
        "name": "viewport", "content": "width=device-width, initial-scale=1"
    })
    t = etree.SubElement(head, "title")
    t.text = title
    style = etree.SubElement(head, "style")
    style.text = _CSS
    return head


def _missing(parent: etree.Element, key: str) -> None:
    p = etree.SubElement(parent, "p", attrib={"class": "missing"})
    p.text = f"[WARNING] '{key}' not found in calibration dict."


def _slug(cam_id: str) -> str:
    return cam_id.replace(" ", "-").replace("/", "-")


# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------

_CSS = """
/* ── Reset & base ─────────────────────────────────────────── */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root {
    --bg:       #0f1117;
    --surface:  #181c24;
    --surface2: #1e2330;
    --border:   #2a2f3d;
    --accent:   #38bdf8;
    --accent2:  #818cf8;
    --warn:     #fbbf24;
    --danger:   #ef4444;
    --text:     #e2e8f0;
    --muted:    #8892a4;
    --radius:   8px;
    --mono:     "JetBrains Mono", "Fira Code", ui-monospace, monospace;
    --sans:     "DM Sans", system-ui, sans-serif;
}

body {
    background: var(--bg);
    color: var(--text);
    font-family: var(--sans);
    font-size: 14px;
    line-height: 1.6;
}

/* ── Header ───────────────────────────────────────────────── */
header {
    background: linear-gradient(135deg, #0f1117 0%, #1a1f2e 100%);
    border-bottom: 1px solid var(--border);
    padding: 32px 40px 24px;
}
header h1 {
    font-size: 26px;
    font-weight: 700;
    letter-spacing: -.5px;
    margin-bottom: 16px;
    background: linear-gradient(90deg, var(--accent), var(--accent2));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

/* ── Nav / TOC ────────────────────────────────────────────── */
nav#toc {
    background: var(--surface);
    border-bottom: 1px solid var(--border);
    padding: 10px 40px;
    display: flex;
    align-items: center;
    gap: 10px;
    flex-wrap: wrap;
    position: sticky;
    top: 0;
    z-index: 100;
}
.nav-label { color: var(--muted); font-size: 12px; }
nav#toc a {
    color: var(--accent);
    text-decoration: none;
    font-size: 12px;
    font-family: var(--mono);
    background: var(--surface2);
    padding: 3px 10px;
    border-radius: 4px;
    border: 1px solid var(--border);
    transition: background .15s;
}
nav#toc a:hover { background: var(--border); }

/* ── Main layout ──────────────────────────────────────────── */
main { padding: 32px 40px; max-width: 1400px; margin: 0 auto; }

/* ── Camera section ───────────────────────────────────────── */
.camera-section {
    margin-bottom: 56px;
    border-left: 3px solid var(--accent2);
    padding-left: 20px;
}
.camera-section h2 {
    font-size: 20px;
    font-weight: 700;
    font-family: var(--mono);
    color: var(--accent2);
    margin-bottom: 12px;
}

/* ── Chip rows ────────────────────────────────────────────── */
.summary-bar, .stats-row {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    margin-bottom: 16px;
}
.chip {
    background: var(--surface2);
    border: 1px solid var(--border);
    border-radius: 20px;
    padding: 4px 12px;
    display: flex;
    gap: 6px;
    align-items: center;
}
.chip-label { color: var(--muted); font-size: 11px; }
.chip-value { color: var(--text);  font-size: 12px; font-weight: 600; font-family: var(--mono); }

/* ── Card grid ────────────────────────────────────────────── */
.card-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
    gap: 16px;
    margin-bottom: 16px;
}
.card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: var(--radius);
    overflow: hidden;
}
.card h3 {
    background: var(--surface2);
    border-bottom: 1px solid var(--border);
    padding: 10px 16px;
    font-size: 12px;
    font-weight: 600;
    letter-spacing: .5px;
    text-transform: uppercase;
    color: var(--muted);
}
.card-body { padding: 14px 16px; }

/* ── Key-value table ──────────────────────────────────────── */
.kv-table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
.kv-table th, .kv-table td { padding: 5px 8px; border-bottom: 1px solid var(--border); }
.kv-table th { color: var(--muted); text-align: left; font-weight: 500; width: 44%; }
.kv-table td { font-family: var(--mono); color: var(--text); }

/* ── Intrinsic matrix ─────────────────────────────────────── */
.matrix-table { border-collapse: collapse; font-family: var(--mono); font-size: 13px;
                margin-bottom: 12px; }
.matrix-table td {
    padding: 4px 10px; text-align: right;
    border: 1px solid var(--border);
    background: var(--surface2);
}

/* ── Plot images ──────────────────────────────────────────── */
.plot-img { width: 100%; height: auto; border-radius: 4px; margin-top: 10px; display: block; }

/* ── Misc ─────────────────────────────────────────────────── */
.warn    { color: var(--warn);   font-size: 12px; }
.missing { color: var(--muted);  font-size: 12px; font-style: italic; }
.back-to-top {
    display: inline-block; margin-top: 8px;
    font-size: 11px; color: var(--muted);
    text-decoration: none;
}
.back-to-top:hover { color: var(--accent); }

footer {
    text-align: center;
    padding: 24px;
    font-size: 11px;
    color: var(--muted);
    border-top: 1px solid var(--border);
    margin-top: 40px;
}
"""

def handle_extension(ext: str):
    import string
    clean_ext = ext.lower()
    clean_ext.translate(str.maketrans('', '', string.punctuation))
    return clean_ext 

def load_images(path: str, extension: str = 'png'):
    """
    Parameters
    ----------
    path : path to folder containing calibration images (for a single camera!)
    extension : which extension to look for when loading images. Default 'png'
    
    Returns
    -------
    imgs : list of loaded images (as numpy arrays)
    paths : list of paths to the images

    """
    imgs = []
    paths = get_all_paths(path, extensions=[extension])
    for path in paths:
        img = load_ldr(path)
        # new_img = (np.sqrt(img/(2**16-1))*255).astype(np.uint8)
        # new_path = path.replace('.tiff', '.png').replace('images_', 'ldr_images_')
        # print(new_path)
        # os.makedirs(os.path.dirname(new_path), exist_ok=True)
        # save_ldr(new_path, new_img)
        imgs += [img]
    return imgs, paths


def detect_markers(imgs: list, charuco: Charuco):
    """
    Parameters
    ----------
    imgs : list of images (all are numpy arrays)
    charuco : Charuco class containing board information for marker detection 
    
    Returns
    -------
    image points : camera pixels of detected charuco corners
    object points : 3D positions corresponding to charuco corners on the board
    ids : ids corresponding to detected charuco markers
    valid_idx : indices of image list that have more than MINIMUM_NUM_MARKERS detected
    invalid_idx : indices of image list that have fewer than MINIMUM_NUM_MARKERS detected
    """
    valid_idx, invalid_idx = set(), set()
    img_points, obj_points, ids = [], [], []
    for idx, img in enumerate(imgs):
        _img_points, _obj_points, _ids = charuco.detect_markers(img)
        if len(_ids) > MINIMUM_NUM_MARKERS:
            valid_idx.add(idx)
        else:
            invalid_idx.add(idx)
        img_points += [_img_points.squeeze()]
        obj_points += [_obj_points.squeeze()]
        ids += [_ids.squeeze()]
    return img_points, obj_points, ids, valid_idx, invalid_idx

def main():
    import time
    tic = time.time()
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--config',
                        default=os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../src/configs/skelevision_tandon_charuco_config.json'), required=False,
                        help='path to charuco config file')
    parser.add_argument('--path', '-p', required=True,
                        help='path to folder containing the calibration data')
    parser.add_argument('--extension', '-e', default='png',
                        help='extension of image file (typically png or tiff) to load')
    parser.add_argument('--debug', action='store_true')

    args, extras = parser.parse_known_args()

    if args.debug:
        print("[DEBUG] Debug printing enabled. Convert to logger...?")


    charuco_config = load_json(args.config)
    charuco = Charuco(board_config=charuco_config)

    if args.debug:
        print("[DEBUG] Received the following charuco configuration file")
        print(charuco_config)

    ext = handle_extension(args.extension)
    if args.debug:
        print("[DEBUG] Received {} extension and cleaned it to {}".format(args.extension, ext))

    calibrations = {} # this will be per camera, with camera id as key
    # the values will be dictionaries containing K, dict_coeffs, T, R, resx, resy

    CAMERA_IDS = get_all_folder_names(args.path)
    if len(CAMERA_IDS) == 0:
        raise RuntimeError("[ERROR] Did not find any folder in provided path {}".format(args.path))
    print("[INFO] Identified {} camera IDs".format(len(CAMERA_IDS)))
    print("[INFO] IDs are: ", CAMERA_IDS)

    for camera_id in CAMERA_IDS:
        # load all images
        imgs, image_paths = load_images(os.path.join(args.path, camera_id), ext)
        if len(image_paths) == 0:
            import warnings
            warnings.warn("[WARNING] Did not find any images in the camera ID {} folder \
                          for the extension {}".format(camera_id, ext))
            continue

        print("[INFO] Loaded {} images for camera ID {} with extension {}".format(len(imgs), camera_id, ext))

        resy, resx = imgs[0].shape[:2] # collect the camera resolution

        if args.debug:
            print("[DEBUG] Camera ID {} resolution: H{} x W{}".format(camera_id, resy, resx))

        # detect markers
        img_points, obj_points, ids, valid_idx, invalid_idx = detect_markers(imgs, charuco)

        labels = [os.path.basename(path) for path in image_paths]
        clean_img_points, clean_obj_points, clean_ids, clean_labels = \
            [img_points[i] for i in valid_idx], [obj_points[i] for i in valid_idx], [ids[i] for i in valid_idx], [labels[i] for i in valid_idx]
        print("[INFO] Cmamera ID {}: {} out of {} ({:.2f}%) images have valid markers".format(camera_id, len(clean_ids), len(ids), len(clean_ids)/len(ids)*100))

        invalid_labels = [labels[i] for i in invalid_idx]
        if args.debug:
            print("[DEBUG] Camera ID {} Invalid indices: {}".format(camera_id, invalid_idx))
            print("[DEBUG] Camera ID {} Invalid labels: {}".format(camera_id, invalid_labels))

        # run calibration
        calibration_result = Calibration.calibrate(object_points=clean_obj_points, 
                                                   image_points=clean_img_points, 
                                                   image_shape=(resx,resy))

        K = calibration_result['K']
        dist_coeffs = calibration_result['dist_coeffs']

        if args.debug:
            print("[DEBUG] Camera ID {} fx {:2f}, fy {:2f}, cx {:2f}, cy {:2f}".format(camera_id,K[0,0], K[1,1], K[0,2], K[1,2]))
            print("[DEBUG] Camera ID {} distortion coefficients: {}".format(camera_id,dist_coeffs))

        intrinsic_path = os.path.join(args.path,camera_id,f'{camera_id}_camera_intrinsics.json')
        print("[INFO] Camera ID {} saving intrinsics in {}".format(camera_id, intrinsic_path))
        save_json(filename=intrinsic_path, data={
            'K': K,
            'dist_coeffs': dist_coeffs,
            'resx': resx,
            'resy': resy
        })
        intrinsic_path = os.path.join(args.path,camera_id,f'{camera_id}_camera_intrinsics.xml')
        # something went wrong with writing the calibration to XML this time... I am reverting to JSON
        write_opencv_calibration_to_xml(intrinsic_path, resx, resy, K, dist_coeffs)

        extrinsic_path = os.path.join(args.path,camera_id,f'{camera_id}_camera_extrinsics_metashape.txt')
        print("[INFO] Camera ID {} saving extrinsics for metashape in {}".format(camera_id, extrinsic_path))
        # save extrinsics for metashape (excluding trouble, which are images with fewer than MINIMUM_NUM_MARKERS)
        save_opencv_extrinsics_for_metashape(extrinsic_path,
                                     labels = clean_labels, 
                                     rvecs = calibration_result['rvecs'],
                                     tvecs = calibration_result['tvecs'])
        
        errors = []

        for img_points, obj_points, rvec, tvec, label \
            in zip(clean_img_points,
                   clean_obj_points,
                   calibration_result['rvecs'],
                   calibration_result['tvecs'],
                   clean_labels):
            _errors = Calibration.reprojection_error(obj_points,
                                                    img_points,
                                                    rvec,
                                                    tvec,
                                                    K,
                                                    dist_coeffs)

            if np.mean(_errors) > ERROR_THRESHOLD:
                import warnings
                warnings.warn('[WARNING] Camera ID {}, label {} has a high reprojection error ({:4f} px) \n \
                              This could indicate its calibration is not good and should be redone.'.format(camera_id, label,np.mean(_errors)))
            
            errors.append(_errors)

        per_view_errors = [np.mean(err) for err in errors]
        
        calibrations[camera_id] = {
            'resx': resx,
            'resy': resy,
            'image_shape': (resx,resy),
            'K': K,
            'dist_coeffs': dist_coeffs,
            'rvecs': calibration_result['rvecs'],
            'tvecs': calibration_result['tvecs'],
            'errors': errors,
            'per_view_errors': per_view_errors,
            'img_points': img_points,
            'clean_img_points': clean_img_points,
            'obj_points': obj_points,
            'clean_obj_points': clean_obj_points,
            'ids': ids,
            'clean_ids': clean_ids,
            'labels': labels,
            'clean_labels': clean_labels,
            'invalid_labels': invalid_labels,
            'valid_idx': valid_idx,
            'invalid_idx': invalid_idx
        }

        # TODO: save for colmap??

    #### generate report
    toc = time.time()
    if args.debug:
        print(f"[DEBUG] Calibrating all cameras took {(toc-tic):02f} seconds")

    print("[INFO] Generating report...")
    generate_report(os.path.join(args.path, 'calibration_report.html'), calibrations)
    toc2 = time.time()
    if args.debug:
        print(f"[DEBUG] Generating report took {(toc2-toc):02f} seconds")

if __name__ == '__main__':
    main()